import type { Locale } from '@/i18n/types'

export type LegalSection = { title: string; paragraphs: string[] }

export type LegalDocument = {
  privacyIntro: string
  privacySections: LegalSection[]
  termsIntro: string
  termsSections: LegalSection[]
  lastUpdated: string
}

const SUPPORT_EMAIL = 'RepLockIssue@outlook.com'

const legalEn: LegalDocument = {
  lastUpdated: 'July 18, 2026',
  privacyIntro:
    'This Privacy Policy describes how RepLock ("we", "us", "our") collects, uses, stores, and protects personal data when you use the RepLock mobile application on iOS and Android and related services (the "Service"). By using the Service, you agree to this policy. If you do not agree, please do not use the Service. The live web version is at https://rutgermb.github.io/App/legal/privacy.html.',
  privacySections: [
    {
      title: '1. Who we are',
      paragraphs: [
        'RepLock is the data controller for personal data processed through the Service, except where we use third-party processors listed below.',
        'For privacy questions, support, deletion requests, or to exercise your rights, contact us at ' +
          SUPPORT_EMAIL +
          '. Support page: https://rutgermb.github.io/App/legal/support.html.',
      ],
    },
    {
      title: '2. Information we collect',
      paragraphs: [
        'Account data: name, email address, and authentication credentials when you register or sign in (via Firebase Authentication).',
        'Workout and progress data: exercises completed, amounts/reps, streaks, earned screen-time balance, difficulty settings, and in-app preferences.',
        'Blocking configuration (when signed in): nicknames/display names you assign, daily opening limits, unlock usage history (usageHistory), related preferences, and opaque identifiers needed to associate your lock list (for example iOS token IDs or Android package names). We do not claim AppBlock-style calendar/time-of-day blocking schedules.',
        'Subscription data: plan type, trial status, and transaction/entitlement identifiers from Apple In-App Purchase, Google Play Billing, and/or RevenueCat. We do not store full payment card numbers.',
        'Technical data: device type, operating system, app version, language, and crash or error diagnostics.',
        'Communications: messages you send to support, and transactional account emails described in the Email communications section.',
        'We do not collect precise GPS / location data for geofencing. We do not use Google Analytics, Meta Pixel, advertising SDKs, or similar third-party advertising / cross-site tracking pixels. We do not currently enable Firebase Analytics (or similar product-analytics SDKs) to build marketing or advertising profiles. If that changes, we will update this policy first. In-app “analytics” features mean your own workout and usage insights from your account data — not third-party ad trackers.',
      ],
    },
    {
      title: '3. App blocking, Screen Time & device data',
      paragraphs: [
        'On Android, with permissions you enable (such as Accessibility and/or Usage Access), RepLock can block selected apps and, where permitted, read device usage statistics for apps you track. Local enforcement stays on your device; package names and nicknames may sync with your account when you are signed in.',
        'On iOS, RepLock uses Apple Family Controls / Screen Time APIs (Managed Settings, Device Activity, Shield Configuration / Shield Action extensions, and related frameworks) that you authorize. Apple presents system UI for selecting apps to shield. Apple restricts what third-party apps can read: we generally cannot obtain the real App Store name or icon of shielded apps for our web UI. You may assign a nickname.',
        'Family Controls selections are identified by opaque tokens generated by Apple. Those selection tokens and active shields are stored on-device (including in an App Group shared with RepLock extensions) and are not uploaded as browsing content. Nicknames and related lock-list metadata may sync with your account when you sign in; opaque Family Controls selection blobs needed to re-apply shields stay device-bound.',
        'We do not read your passwords, messages, photos, browsing history inside blocked apps, or the full contents of other apps. We do not use blocking data for advertising profiles. Blocking depends on OS permissions and platform rules; we do not claim it works in every edge case.',
      ],
    },
    {
      title: '4. What syncs when you are signed in',
      paragraphs: [
        'When you are signed in (and not using a local-only development session), RepLock may sync workouts, screen-time balance, streaks, preferences, app nicknames and lock-list metadata, daily opening limits, and usageHistory to Firebase Firestore (or a legacy sync backend where applicable).',
        'Device-only: Family Controls / Screen Time selection encodings, App Group unlock maps, and Managed Settings shields remain on the device. Subscription Pro status is validated via Apple/Google and RevenueCat rather than written solely by the client as billing truth.',
      ],
    },
    {
      title: '5. Push notifications',
      paragraphs: [
        'If you allow notifications, the OS may grant RepLock permission to send push or local notifications (for example workout reminders or trial-related notices when those features are enabled). You can change this in system Settings or in the app. Token registration may use APNs or Google services. Reminder content may roll out over time; granting permission does not mean every reminder type is already active.',
      ],
    },
    {
      title: '6. How we use your data',
      paragraphs: [
        'To provide and operate the Service, including earning screen time through workouts and enforcing limits you configure.',
        'To sync progress and settings across devices when you sign in.',
        'To process subscriptions, free trials, restores, and entitlement checks (including via RevenueCat).',
        'To send service-related messages if you enable notifications, and transactional account emails.',
        'To improve reliability, fix bugs, and understand aggregated product usage from our own systems (not third-party ad networks).',
        'To comply with legal obligations and protect our rights and users\' safety.',
      ],
    },
    {
      title: '7. Legal bases (EEA/UK)',
      paragraphs: [
        'We process data based on: (a) performance of our contract with you; (b) your consent where required (e.g. optional notifications or certain device permissions); (c) legitimate interests such as security and product improvement; and (d) legal obligations.',
        'You may withdraw consent at any time without affecting the lawfulness of processing before withdrawal.',
      ],
    },
    {
      title: '8. Sharing with third parties (service providers)',
      paragraphs: [
        'We share personal data with service providers only as needed to run the Service. These providers act as processors / service providers on our behalf (or as independent controllers for store billing), not as advertising partners buying your data for ads:',
        '• Firebase (Google) — Authentication and Firestore (or similar) cloud sync. Firebase Analytics for advertising is not enabled.',
        '• Apple — In-App Purchases, App Store subscriptions, Screen Time / Family Controls, and APNs where applicable.',
        '• Google — Google Play Billing on Android and related mobile services you enable.',
        '• RevenueCat — subscription status, receipt validation, and entitlement syncing on mobile.',
        '• Hosting and infrastructure providers (including GitHub Pages for public legal/support pages).',
        'Providers process data under their own privacy policies and our instructions (where they are processors). We may disclose data if required by law or to protect safety and rights.',
        'California (CCPA/CPRA) — “sale” and “share”: We do not sell your personal information for money. We also do not “share” personal information for cross-context behavioral advertising as those terms are defined under California law. Disclosures to the service providers listed above are for operating the Service (account sync, auth, billing, hosting), not for selling or sharing data with ad networks. We do not operate a “Do Not Sell or Share My Personal Information” opt-out link because we do not sell or share for advertising in that sense. If we ever introduce advertising trackers or practices that would constitute a sale or share under CCPA/CPRA, we will update this policy and provide required notices/opt-outs first.',
      ],
    },
    {
      title: '9. Retention',
      paragraphs: [
        'Account and workout data: kept while your account is active.',
        'After you delete your account (Settings → Delete account), we delete or anonymize personal data on our servers within a reasonable period, except where we must retain data for legal, tax, or dispute-resolution purposes. Backup copies may persist for a limited time before automatic deletion.',
        'Support emails: retained as needed to handle your request and for a limited period afterward for security and continuity.',
        'On-device App Group / Screen Time configuration may remain until you revoke permissions or uninstall the app. Store subscriptions are controlled by Apple or Google and are not cancelled merely by deleting the RepLock account.',
      ],
    },
    {
      title: '10. Security',
      paragraphs: [
        'We use technical and organizational measures to protect personal data, including encryption in transit, access controls, and secure authentication.',
        'No method of transmission or storage is 100% secure. Keep your login credentials confidential.',
      ],
    },
    {
      title: '11. Log & diagnostic data',
      paragraphs: [
        'If the app crashes or errors occur, we may collect diagnostic information (device model, OS version, app version, error timestamps). This data is used to improve stability and is not used to identify you beyond your account when you are signed in.',
      ],
    },
    {
      title: '12. Your rights',
      paragraphs: [
        'Depending on your location (including EEA/UK under GDPR and California under CCPA/CPRA), you may have the right to: (i) access your personal data; (ii) rectify inaccurate data; (iii) erase data (“right to be forgotten”) when applicable; (iv) restrict processing; (v) data portability; (vi) object to certain processing based on legitimate interests; (vii) withdraw consent where processing is based on consent; and (viii) for California residents, know, delete, and correct personal information, and not be discriminated against for exercising these rights.',
        'How to delete: open the app → Settings → Delete account, then confirm with your password. This removes your Firebase Auth user and associated cloud app state (or equivalent server account) and clears local app storage. Device Screen Time / App Group data may remain until you revoke access or uninstall. Cancel App Store / Google Play subscriptions separately (Settings → Manage subscription, or your store account).',
        'You may also email ' +
          SUPPORT_EMAIL +
          ' from the address on your account to request deletion or other rights. We may need to verify your identity. EEA/UK users may lodge a complaint with their local data protection authority.',
      ],
    },
    {
      title: '13. Children',
      paragraphs: [
        'The Service is not directed at children under 13 (or the minimum age in your country). We do not knowingly collect data from children. Contact us if you believe a child has provided personal data so we can delete it.',
      ],
    },
    {
      title: '14. International transfers',
      paragraphs: [
        'Your data may be processed in countries outside your own (including by Firebase/Google, Apple, or RevenueCat). Where required, we use appropriate safeguards such as standard contractual clauses approved by the European Commission.',
      ],
    },
    {
      title: '15. Public website & cookies',
      paragraphs: [
        'Our public legal and support pages (hosted on GitHub Pages) are informational. They may use only strictly necessary cookies or similar technologies provided by the host for security and delivery. We do not run advertising trackers on those pages.',
      ],
    },
    {
      title: '16. Email communications (CAN-SPAM)',
      paragraphs: [
        'Today: we send only transactional / account emails needed to operate the Service — for example email verification and password-reset messages sent through Firebase Authentication. We do not currently send marketing or promotional email campaigns (newsletters, offers, or ads).',
        'If we start marketing email: we will update this policy and follow applicable requirements (including U.S. CAN-SPAM practices): honest subject lines, clear identification of the sender, a working unsubscribe mechanism in each marketing message, and a valid physical mailing address in those messages (and listed here). Until marketing begins, support contact remains ' +
          SUPPORT_EMAIL +
          '. Operators: replace this sentence with your real business street address before sending any marketing email — for example: “Physical mailing address: [Street, City, State/Province, Postal code, Country].”',
      ],
    },
    {
      title: '17. Changes to this policy',
      paragraphs: [
        'We may update this Privacy Policy from time to time. We will post the new version in the app and at https://rutgermb.github.io/App/legal/privacy.html and update the "Last updated" date. Material changes may require renewed consent where applicable.',
      ],
    },
  ],
  termsIntro:
    'Please read these Terms of Service ("Terms") carefully before using RepLock. Your access to and use of the Service is conditioned on your acceptance of these Terms. The live web version is at https://rutgermb.github.io/App/legal/terms.html.',
  termsSections: [
    {
      title: '1. Acceptance',
      paragraphs: [
        'By accessing or using RepLock, you agree to be bound by these Terms and our Privacy Policy. If you disagree, you may not use the Service.',
        'You must be old enough to form a binding contract in your jurisdiction and comply with all applicable laws.',
      ],
    },
    {
      title: '2. The Service',
      paragraphs: [
        'RepLock helps you earn screen time through exercise and manage access to distracting apps according to rules you set. On iOS, blocking uses Apple Family Controls / Screen Time APIs you authorize. On Android, blocking may use Accessibility, Usage Access, and related permissions you enable.',
        'Features vary by platform, OS version, permissions, and subscription plan. We may modify, suspend, or discontinue features with reasonable notice where practicable.',
      ],
    },
    {
      title: '3. Subscriptions & In-App Purchases',
      paragraphs: [
        'RepLock Pro and related paid features are offered on a subscription basis through the Apple App Store and/or Google Play Store. Payment is charged to your store account (Apple ID or Google Play). Before you confirm purchase, the app and/or store purchase sheet show the price, billing period (for example monthly or yearly), and any free-trial details that apply.',
        'Auto-renewal: Subscriptions renew automatically at the then-current price for the same period unless you cancel at least 24 hours before the end of the current period. Your store account will be charged for renewal within 24 hours prior to the end of the current period.',
        'How to cancel: Open RepLock → Settings → Manage subscription (opens Apple or Google subscription management / Customer Center), or cancel in your device store account settings (iOS: Settings → [Your Name] → Subscriptions; Android: Google Play → Payments & subscriptions). Cancel anytime; you keep Pro access until the end of the period you already paid for. Deleting the app or your RepLock account does not cancel a store subscription by itself.',
        'We use RevenueCat (and Apple/Google billing) to validate purchases and sync entitlement status. Refunds are handled by Apple or Google according to their policies.',
      ],
    },
    {
      title: '4. Free trial',
      paragraphs: [
        'We may offer a free trial of Pro features. When the trial ends, your account may revert to the free tier unless you subscribe.',
        'We may change or end free trial offers at any time. Trial eligibility may be limited. If a store trial converts to a paid subscription, the price and period shown at purchase apply after the trial unless you cancel as described above.',
      ],
    },
    {
      title: '5. App blocking & platform limits',
      paragraphs: [
        'You are responsible for granting and maintaining required permissions. We do not guarantee uninterrupted blocking. OS updates, revoked permissions, or platform policy changes may affect functionality.',
        'On iOS, Apple privacy rules may prevent RepLock from reading real app names into the in-app list; nicknames you enter are your responsibility.',
      ],
    },
    {
      title: '6. Acceptable use',
      paragraphs: [
        'Use RepLock only for personal wellbeing and lawful purposes.',
        'You may not reverse engineer the app (except where mandatory law allows), circumvent blocking or subscription limits, abuse trials, or use the Service to violate third-party rights.',
        'We may suspend or terminate accounts that violate these Terms.',
      ],
    },
    {
      title: '7. Health & fitness disclaimer',
      paragraphs: [
        'RepLock is not medical advice and does not replace professional healthcare. Consult a physician before starting any exercise program.',
        'You exercise at your own risk. We are not liable for injuries or health outcomes from workouts performed using the app.',
      ],
    },
    {
      title: '8. Intellectual property',
      paragraphs: [
        'RepLock, its logo, design, and content are owned by us or our licensors and protected by intellectual property laws. You receive a limited, non-exclusive, non-transferable license to use the app for personal use.',
        'You may not copy, modify, or distribute the Service without our written permission.',
      ],
    },
    {
      title: '9. Third-party services & links',
      paragraphs: [
        'The Service integrates third-party services including Apple, Google/Firebase, and RevenueCat. We are not responsible for their content or practices. Review their terms and privacy policies.',
      ],
    },
    {
      title: '10. Disclaimer of warranties',
      paragraphs: [
        'THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.',
        'We do not warrant uninterrupted, error-free, or secure operation, or that blocking will work on every device or app.',
      ],
    },
    {
      title: '11. Limitation of liability',
      paragraphs: [
        'TO THE MAXIMUM EXTENT PERMITTED BY LAW, REPLOCK AND ITS AFFILIATES SHALL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR LOSS OF PROFITS, DATA, OR GOODWILL.',
        'Our total liability for any claim relating to the Service shall not exceed the amount you paid us in the twelve months before the claim, or EUR 50 if you used the free plan.',
        'Some jurisdictions do not allow certain limitations; in those cases our liability is limited to the fullest extent permitted by law.',
      ],
    },
    {
      title: '12. Termination',
      paragraphs: [
        'You may stop using the Service and delete your account at any time in Settings → Delete account. Deleting the app or account does not automatically cancel a store subscription — cancel via Settings → Manage subscription or in Apple or Google subscription settings.',
        'We may suspend or terminate access if you breach these Terms or if required for legal or security reasons.',
      ],
    },
    {
      title: '13. Governing law',
      paragraphs: [
        'These Terms are governed by the laws of the Netherlands, without regard to conflict-of-law rules, unless mandatory consumer protection laws in your country require otherwise.',
        'Disputes should first be raised with ' + SUPPORT_EMAIL + '. EU consumers may also use online dispute resolution platforms.',
      ],
    },
    {
      title: '14. Changes',
      paragraphs: [
        'We may update these Terms. Material changes will be communicated in the app or by email where appropriate. Continued use after changes take effect constitutes acceptance where permitted by law.',
      ],
    },
    {
      title: '15. Contact',
      paragraphs: [
        'Questions about these Terms: ' +
          SUPPORT_EMAIL +
          '. Support page: https://rutgermb.github.io/App/legal/support.html',
      ],
    },
  ],
}

const PRIVACY_TITLES = {
  de: [
    '1. Wer wir sind',
    '2. Welche Daten wir erheben',
    '3. App-Blockierung, Screen Time & Gerätedaten',
    '4. Was bei Anmeldung synchronisiert wird',
    '5. Push-Benachrichtigungen',
    '6. Wie wir Daten nutzen',
    '7. Rechtsgrundlagen (EWR/VK)',
    '8. Weitergabe an Dritte (Dienstleister)',
    '9. Aufbewahrung',
    '10. Sicherheit',
    '11. Protokoll- & Diagnosedaten',
    '12. Deine Rechte',
    '13. Kinder',
    '14. Internationale Übermittlung',
    '15. Öffentliche Website & Cookies',
    '16. E-Mail-Kommunikation (CAN-SPAM)',
    '17. Änderungen',
  ],
  fr: [
    '1. Qui nous sommes',
    '2. Données collectées',
    '3. Blocage d\'apps, Screen Time & données appareil',
    '4. Ce qui se synchronise une fois connecté',
    '5. Notifications push',
    '6. Utilisation des données',
    '7. Bases légales (EEE/RU)',
    '8. Partage avec des tiers (prestataires)',
    '9. Conservation',
    '10. Sécurité',
    '11. Journaux & diagnostics',
    '12. Tes droits',
    '13. Enfants',
    '14. Transferts internationaux',
    '15. Site public & cookies',
    '16. Communications e-mail (CAN-SPAM)',
    '17. Modifications',
  ],
  es: [
    '1. Quiénes somos',
    '2. Datos que recopilamos',
    '3. Bloqueo de apps, Screen Time y datos del dispositivo',
    '4. Qué se sincroniza al iniciar sesión',
    '5. Notificaciones push',
    '6. Cómo usamos los datos',
    '7. Bases legales (EEE/RU)',
    '8. Compartir con terceros (proveedores)',
    '9. Conservación',
    '10. Seguridad',
    '11. Registros y diagnósticos',
    '12. Tus derechos',
    '13. Menores',
    '14. Transferencias internacionales',
    '15. Sitio público y cookies',
    '16. Comunicaciones por correo (CAN-SPAM)',
    '17. Cambios',
  ],
} as const

const TERMS_TITLES = {
  de: [
    '1. Annahme',
    '2. Der Dienst',
    '3. Abonnements & In-App-Käufe',
    '4. Kostenlose Testphase',
    '5. App-Blockierung & Plattformlimits',
    '6. Zulässige Nutzung',
    '7. Gesundheit & Fitness',
    '8. Geistiges Eigentum',
    '9. Dienste Dritter',
    '10. Haftungsausschluss',
    '11. Haftungsbeschränkung',
    '12. Kündigung',
    '13. Anwendbares Recht',
    '14. Änderungen',
    '15. Kontakt',
  ],
  fr: [
    '1. Acceptation',
    '2. Le Service',
    '3. Abonnements & achats in-app',
    '4. Essai gratuit',
    '5. Blocage d\'apps & limites plateforme',
    '6. Utilisation acceptable',
    '7. Santé & fitness',
    '8. Propriété intellectuelle',
    '9. Services tiers',
    '10. Exclusion de garanties',
    '11. Limitation de responsabilité',
    '12. Résiliation',
    '13. Droit applicable',
    '14. Modifications',
    '15. Contact',
  ],
  es: [
    '1. Aceptación',
    '2. El Servicio',
    '3. Suscripciones y compras in-app',
    '4. Prueba gratuita',
    '5. Bloqueo de apps y límites plataforma',
    '6. Uso aceptable',
    '7. Salud y fitness',
    '8. Propiedad intelectual',
    '9. Servicios de terceros',
    '10. Exención de garantías',
    '11. Limitación de responsabilidad',
    '12. Terminación',
    '13. Ley aplicable',
    '14. Cambios',
    '15. Contacto',
  ],
} as const

function localizeTitles(
  sections: LegalSection[],
  titles: readonly string[]
): LegalSection[] {
  return sections.map((s, i) => ({
    ...s,
    title: titles[i] ?? s.title,
  }))
}

/** German, French, Spanish: localized section titles; English body as source of truth. */
const legalDe: LegalDocument = {
  ...legalEn,
  lastUpdated: '18. Juli 2026',
  privacyIntro:
    'Diese Datenschutzerklärung beschreibt, wie RepLock personenbezogene Daten erhebt, nutzt und schützt, wenn du die RepLock-App und zugehörige Dienste („Dienst") nutzt.',
  termsIntro:
    'Bitte lies diese Nutzungsbedingungen („Bedingungen") sorgfältig, bevor du RepLock verwendest.',
  privacySections: localizeTitles(legalEn.privacySections, PRIVACY_TITLES.de),
  termsSections: localizeTitles(legalEn.termsSections, TERMS_TITLES.de),
}

const legalFr: LegalDocument = {
  ...legalEn,
  lastUpdated: '18 juillet 2026',
  privacyIntro:
    'Cette politique de confidentialité décrit comment RepLock collecte, utilise et protège les données personnelles lorsque tu utilises l\'application RepLock et les services associés (le « Service »).',
  termsIntro:
    'Lis attentivement ces Conditions d\'utilisation (« Conditions ») avant d\'utiliser RepLock.',
  privacySections: localizeTitles(legalEn.privacySections, PRIVACY_TITLES.fr),
  termsSections: localizeTitles(legalEn.termsSections, TERMS_TITLES.fr),
}

const legalEs: LegalDocument = {
  ...legalEn,
  lastUpdated: '18 de julio de 2026',
  privacyIntro:
    'Esta Política de privacidad describe cómo RepLock recopila, usa y protege los datos personales cuando utilizas la aplicación RepLock y los servicios relacionados (el «Servicio»).',
  termsIntro:
    'Lee estos Términos de servicio («Términos») con atención antes de usar RepLock.',
  privacySections: localizeTitles(legalEn.privacySections, PRIVACY_TITLES.es),
  termsSections: localizeTitles(legalEn.termsSections, TERMS_TITLES.es),
}

const documents: Record<Locale, LegalDocument> = {
  en: legalEn,
  nl: {
    ...legalEn,
    lastUpdated: '18 juli 2026',
  },
  de: legalDe,
  fr: legalFr,
  es: legalEs,
}

export function getLegalDocument(locale: Locale): LegalDocument {
  return documents[locale] ?? documents.en
}
